# Generated by Django 2.0.7 on 2018-08-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dataset_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_table_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=50)),
                ('field_2', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'test_table_1',
            },
        ),
    ]
