# Generated by Django 2.0.7 on 2018-08-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_test_table_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_table_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_3', models.IntegerField()),
                ('field_4', models.TextField()),
            ],
            options={
                'db_table': 'test_table_2',
            },
        ),
    ]
