# Generated by Django 2.0.7 on 2018-08-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_test_table_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataset_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=50)),
                ('field_4', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='dataset_1',
        ),
        migrations.DeleteModel(
            name='test_table_1',
        ),
        migrations.DeleteModel(
            name='test_table_2',
        ),
    ]
