# Generated by Django 2.0.7 on 2018-08-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180820_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataset_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(blank=True, max_length=50)),
                ('field_4', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dataset_3',
        ),
    ]
