# Generated by Django 2.0.7 on 2018-08-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dataset_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dataset_2',
        ),
        migrations.DeleteModel(
            name='test_table_2',
        ),
    ]
