version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      # - frontend
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile-dev
    volumes:
      - ./services/backend/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - PYTHONPATH=/usr/src/app
    env_file:
      - env_variables.env
    depends_on:
      - db
    links:
      - db
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile-prod
    volumes:
      - './services/frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    env_file:
      - env_variables.env
    depends_on:
      - backend
  db:
    build:
      context: ./services/backend/backend/db
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume: