apiVersion: v1
kind: Secret
metadata:
  name: db-passwords
data:
  djangouserpw: c2hhcmExMjM0Cg==
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: postgres-data
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001/"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres-pragyaam
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdata
          mountPath: /usr/local/var/postgres
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgres-data
      - name: secrets
        secret: 
          secretName: db-passwords
---
metadata:
  name: postgres
kind: Service
apiVersion: v1
spec:
  ports:
  - name:  posgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    name: Postgres