# Generated by Django 2.0.7 on 2018-09-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180905_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset_2',
            name='Sales Date',
        ),
        migrations.AddField(
            model_name='dataset_2',
            name='DOB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
