# Generated by Django 2.0.7 on 2018-09-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_worksheet 2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worksheet 2',
        ),
    ]
